export const UI_OPEN_DRAWER = 'UI_OPEN_DRAWER';
export const UI_CLOSE_DRAWER = 'UI_CLOSE_DRAWER';
export const UI_UPDATE_TITLE = 'UI_UPDATE_TITLE';
export const UI_UPDATE_THEME = 'UI_UPDATE_THEME';
export const UI_UPDATE_DRAWER_TYPE = 'UI_UPDATE_DRAWER_TYPE';
export const UI_SHOW_OVERLAY = 'UI_SHOW_OVERLAY';
export const UI_HIDE_OVERLAY = 'UI_HIDE_OVERLAY';

// Documentation Constants
export const SEARCH_FOR_COMPONENT = 'SEARCH_FOR_COMPONENT';
export const START_QUICK_SEARCHING = 'START_QUICK_SEARCHING';
export const STOP_QUICK_SEARCHING = 'STOP_QUICK_SEARCHING';
export const INITIALIZE_COLORS = 'INITIALIZE_COLORS';


// Toast Constants
export const ADD_TOAST = 'ADD_TOAST';
export const DISMISS_TOAST = 'DISMISS_TOAST';
